version: "3.7"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: ayp-group
    container_name: ayp-group-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./docker/supervisor.conf:/etc/supervisord.conf
      - ./docker/php.ini:/usr/local/etc/php/conf.d/app.ini
      - ./docker/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./docker/nginx.conf:/etc/nginx/sites-enabled/default
    ports:
      - 8082:80
    entrypoint: [bash, ./docker/run.sh]
    networks:
      - ayp_group_network
  db:
    image: mariadb
    container_name: ayp-group-db
    restart: unless-stopped
    ports:
      - 3308:3306
    environment:
      MYSQL_DATABASE: ayp-group
      MYSQL_ROOT_PASSWORD: ayp-group
    working_dir: /var/www/
    volumes:
      - dbdata:/var/lib/mysql/
      - ./:/var/www
    networks:
      - ayp_group_network

networks:
  ayp_group_network:
    driver: bridge

volumes:
  dbdata:
    driver: local
